Splitted off the main part into a .py file to make it easier to use the macro in scripts
FreeCAD/FreeCAD-macros pull request #120
Opened 2022-02-26 08:18 UTC by chbergmann

Thank you for creating a pull request to contribute to FreeCAD-macros!
To integrate your macro please make sure the following steps are complete:

- [ ] Please check this box if you're not submitting a new macro.   
- [ ] Are you submitting a new macro ?  
- [ ] Have you followed the ['How to submit a macro'](../README.md#how-to-submit-a-macro) section of the README.md ?  
- [ ] Your macro has a [Description](../README.md#macro-description) in its header.  
- [ ] Your macro has a [CamelCase name](../README.md#camelcase-macro-name).  
- [ ] Your macro is named [appropriately](../README.md#macro-name-specifics).  
- [ ] Your macro contains a [Metadata section](../README.md#macro-metadata) that immediately follows the header description.  
- [ ] Your macro is Python3/Qt5 compliant and tested on the latest FreeCAD stable and development releases.  
- [ ] You're including documentation on how your macro works (bonus: screenshots and/or video on the Wiki)  
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)  
- [ ] Commit message is titled in the following way `[MacroName] Short description`.
- [ ] Optional, write or update the changelog in the macro, from latest to oldest.

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2022-02-26 22:11 UTC, luzpaz commented
It would also be beneficial to add and icon to the `__icon__` in the metadata portion of the macro

2022-03-02 12:12 UTC, galou requested changes
Thanks for the changes. Please consider my comments about cosmetic things.

2022-03-02 12:12 UTC, galou commented on ImportExport/ObjectsToPython.FCMacro
> +__Icon__ = 'ObjectsToPython/toconsole.svg'
Can you please rename `ObjectsToPython/toconsole.svg` to `ObjectsToPython.svg`?

2022-03-02 12:12 UTC, galou commented on ImportExport/ObjectsToPython.FCMacro
> +__Date__ = '2021-07-17'
Please use today's date.

2022-03-02 12:12 UTC, galou commented on TechDraw/LasercutterSVGExport.FCMacro
>          gui.doCommand("LasercutterTechdrawExport.makeLasercutterTechdrawExport(lcparts, BeamWidth = %f, doc = App.activeDocument())"%self.form.doubleSpinBox.value())
Do you know `gui.doCommand(f'LasercutterTechdrawExport.makeLasercutterTechdrawExport(lcparts, BeamWidth={self.form.doubleSpinBox.value()}, doc=FreeCAD.activeDocument())')`?

I mainly wanted to mention formatted strings but I changed a few other details according to Python standard and consistency between the use of `FreeCAD` and `App`.

2022-03-04 06:25 UTC, galou requested changes
Sorry that I missed a few things in the last review. Thanks for your patience.

2022-03-04 06:25 UTC, galou commented on ImportExport/ObjectsToPython.FCMacro
> +__Files__ = 'ObjectsToPython/README.md,ObjectsToPython/ObjectsToPython.ui,ObjectsToPython/toconsole.svg'
`ObjectsToPython.svg` it meant in place of `ObjectsToPython/toconsole.svg`.

2022-03-04 06:25 UTC, galou commented on TechDraw/LasercutterSVGExport.FCMacro
>  __Version__ = '0.7'
`__Version__ = '0.7.0'`

2022-03-04 06:25 UTC, galou commented on ImportExport/ObjectsToPython.FCMacro
> +__Version__ = '0.7'
`__Version__ = 0.7.0`

2022-03-05 13:06 UTC, merged

2022-03-05 13:06 UTC, galou commented
Thanks!