treeHelper macro initial commit
FreeCAD/FreeCAD-macros pull request #143
Opened 2022-09-24 19:01 UTC by iinjdpa

Thank you for creating a pull request to contribute to FreeCAD-macros!
To integrate your macro please make sure the following steps are complete:

- [ ] Please check this box if you're not submitting a new macro.   
- [ x ] Are you submitting a new macro ?  
- [ x ] Have you followed the ['How to submit a macro'](../README.md#how-to-submit-a-macro) section of the README.md ?  
- [ x ] Your macro has a [Description](../README.md#macro-description) in its header.  
- [ x ] Your macro has a [CamelCase name](../README.md#camelcase-macro-name).  
- [ x ] Your macro is named [appropriately](../README.md#macro-name-specifics).  
- [ x ] Your macro contains a [Metadata section](../README.md#macro-metadata) that immediately follows the header description.  
- [ x ] Your macro is Python3/Qt5 compliant and tested on the latest FreeCAD stable and development releases.  
- [ x ] You're including documentation on how your macro works (bonus: screenshots and/or video on the Wiki)  
- [ x ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)  
- [ x ] Commit message is titled in the following way `[MacroName] Short description`.
- [ ] Optional, write or update the changelog in the macro, from latest to oldest.

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2022-09-25 03:24 UTC, luzpaz commented
No spaces in the `[x]` will activate the markdown checklist like so:  
- [x]

2022-09-25 07:25 UTC, iinjdpa commented
I edited the markdown. Thank you.

2022-09-25 14:32 UTC, luzpaz commented
@iinjdpa do you mind opening a forum thread introducing the macro, perhaps with some screenshots ?

2022-09-25 19:32 UTC, iinjdpa commented
@luzpaz I have an old post opened in forum about treeHelper. I will update this post with last functionalities of treeHelper.
I have a youtube video where I have showed treeHelper. I have made an update from youtube video version where treeHelper inherit from QDockWidget.

forum thread url: https://forum.freecadweb.org/viewtopic.php?style=1&f=22&t=63807&p=628636#p628636

2022-11-13 16:19 UTC, galou requested changes
Thank you for your contribution, a few corrections are required before I can merge:
- Name the macro `TreeHelp.FCMacro` and the icon `TreeHelper.svg`.
- Put the icon at the same level as the macro.
- Remove the trailing slash ('/') in `__Files__`.
- Rename the directory `tree_helper`.
- Use the ui file instead of the generated Python file.
- Other inline comments.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +    def __init__(self):
Skip `__init__` entirely if not used.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +from PySide import QtCore, QtGui
Please state that this is FreeCAD's custom PySide, unfortunately.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +        if doc == None:
`if doc is None:`

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +            doc = FreeCAD.newDocument()
Why do you create a new document? I though that the macro helps to sort the tree. A new document has no objects to sort.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +        docName = doc.Name
Is the variable really necessary? `doc.Name` appears just as short and clear as `docName`.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +import FreeCAD as App
Please use `app` and `gui` for consistency with other macros.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +        super(TreeDrops, self).__init__(parent=None)
Prefer `super().__init__(parent=None)`. I guess that `super().__init__(parent)` is the correct call anyway.

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper.FCMacro
> +                if len(obj_by_label) > 1:
What about `if obj_by_label`?

2022-11-13 16:19 UTC, galou commented on Utility/treeHelper/ui_treewindow.py
> +from PySide2 import QtCore, QtGui, QtWidgets
Please upload the ui file and replace with `gui.PySideUic.loadUiType('relative_path_to_ui_file')`. Cf. https://github.com/FreeCAD/FreeCAD-macros/wiki/Dynamically-load-graphical-interface-definition.

2023-02-19 20:32 UTC, galou commented
@iinjdpa do you have the time to have a look at my suggestions?

2023-08-11 07:14 UTC, merged