Support for link when ElementCount > 0
FreeCAD/FreeCAD-macros pull request #156
Opened 2023-02-05 19:55 UTC by Jolbas

When a App::Link property ElementCount was set to 1 or higher, the macro couldn't follow and the macro reported the placement of the root object instead.

2023-02-12 23:55 UTC, luzpaz commented on Information/GetGlobalPlacement.FCMacro
> +    This is in contrast with``object.getGlobalPlacement()`` that returns the placement of the original
missing whitespace between 'with' and object.getGlobalPlacement()

2023-02-13 12:15 UTC, luzpaz requested changes

2023-02-13 12:15 UTC, luzpaz commented on Information/GetGlobalPlacement.FCMacro
> +        # This seems to be nessecary on ``Part::*`` objects,``PartDesign::Body' etc.
space after comma

2023-02-13 13:28 UTC, galou requested changes
Thanks for the contribution.

I didn't finish my review because I noticed that your version returns an error with a `Part::Box`  and a `Part::Link` to it. When selecting the link I get the error:
```
14:19:02  Traceback (most recent call last):
  File "/home/gael/.local/share/FreeCAD/Macro/GetGlobalPlacementJolbas.FCMacro", line 142, in <module>
    get_and_print_selected_placements()
  File "/home/gael/.local/share/FreeCAD/Macro/GetGlobalPlacementJolbas.FCMacro", line 132, in get_and_print_selected_placements
    wo_subelement = strip_subelement(sub_fullpath)
<class 'NameError'>: name 'strip_subelement' is not defined
```

Can you please have a look at that? Thanks!

Do you have some files that didn't work with the original macro that we could use as test-case?

2023-02-13 13:28 UTC, galou commented on Information/GetGlobalPlacement.FCMacro
> +    mx = None
`mx` as a variable name is not relevant. Can you be more explicit?

2023-02-13 14:21 UTC, galou commented on Information/GetGlobalPlacement.FCMacro
> +    return get_global_placement_and_scale(object, subobject_fullpath)[0]
The case where `get_global_placement_and_scale()` returns `None` is not handled.

2023-02-13 14:41 UTC, Jolbas commented
Thanks for test and review. I have a look.

2023-02-13 15:31 UTC, galou commented
I went ahead and integrated your changes. 
@Jolbas can you double-check my changes?
@Jolbas, I added you as author of the macro and commit author.

2023-02-13 15:31 UTC, closed without merging

2023-02-13 15:34 UTC, galou commented
@Jolbas I added a test file that helped me see what was wrong in the original macro. Maybe you can add a test with a link array.

2023-02-15 13:39 UTC, Jolbas commented
@galou   Have done som additional fixes in https://github.com/FreeCAD/FreeCAD-macros/pull/158